update

diff --git a/.github/workflows/cypress-test.yml b/.github/workflows/cypress-test.yml
--- a/.github/workflows/cypress-test.yml
+++ b/.github/workflows/cypress-test.yml
@@ -82,15 +82,15 @@ jobs:
           path: test-report-summary.md
           recreate: true
 
-      - name: Make build pass or fail or test results after creating the report
-        if: env.build_failed == 'true'
-        run: |
-          echo "Some tests failed. Failing the build."
-          exit 1
-
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: cypress/reports
           publish_branch: gh-pages
+
+      - name: Make build pass or fail or test results after creating the report
+        if: env.build_failed == 'true'
+        run: |
+          echo "Some tests failed. Failing the build."
+          exit 1
